version: "3"

services:
  db:
    image: mysql:5.7
    env_file: ./mysql.env
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d/
    networks:
      - database
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=password
    ports:
      - 8080:80
    networks:
      - database
    depends_on:
      - db

  app:
    image: node:12
    env_file: ./mysql.env
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_SERVER=db
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app
    working_dir: /app
    command: npm run dev
    networks:
      - backend
    depends_on:
      - db

networks:
  backend:
  database:
